target 'DoYuLiveStreaming' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoYuLiveStreaming
pod 'AFNetworking', '~> 3.1.0'


end
